---
- hosts: all              
  gather_facts: false
  tasks:
    - name: Get scan start time
      set_fact: 
        scan_start_time: "{{ now() }}"
      run_once: true

    - name: Execute osquery
      command: osqueryi --json "{{ item['query'] }}"
      loop: "{{ queries }}"
      register: r

    - name: Insert query result to PostgreSQL DB
      postgresql_query:
        login_host: "{{ pgsql_host }}"
        port: "{{ pgsql_port }}"
        login_user: "{{ pgsql_user }}"
        login_password: "{{ pgsql_pass }}"
        db: "{{ pgsql_database }}"
        query: INSERT INTO "{{ pgsql_table }}" (hostname, scan_date, query, result) VALUES (%s, %s, %s, %s)
        positional_args:
          - "{{ inventory_hostname }}"
          - "{{ scan_start_time }}"
          - "{{ item['item'].name }}"
          - "{{ item['stdout'] | from_json | to_json }}"
      loop: "{{ r.results }}"
      delegate_to: localhost
      no_log: True
